#!/bin/bash

maxLen=0

# When there more than one argument passed in
if [ "$#" -gt 1 ]
then
  echo "Error: Please enter one specific directory."
  exit -1
else
  if [ "$#" -eq 1 ]
  then
    path="$1"
    if [ ! -d "$path" ] || [ ! -d .git ]
      then
      echo "Error: Please enter a correct directory."
      exit -1
    else
      cd "$1"
    fi
  fi
  # Looking for the longest filename for padding later
  for file in `git ls-files`
  do
  len=${#file}
    if [ $len -gt $maxLen ]
    then
      maxLen=$len
    fi
  done

fi

if [ "$#" -eq 0 ] || [ "$#" -eq 1 ]
then

  for file in `git ls-files`
  do
  #Getting the time-stamp
  date=$(git log -n 1 --pretty=%cI $file)

  #Getting the revision id
  revision_id=$(git log -n 1 --abbrev=5 --pretty=%h $file)

  #Getting the author
  author=$(git log -n 1 --pretty=%an $file)

  printf "%s [%s]: %-${maxLen}s (%s)\n" "$date" "$revision_id" $file "$author"

done | sort -k 1,1 -r -k 3,3b

  for files in `git ls-files --others`
  do
    echo "[***not under version control***]: $files"
  done | sort -k 3,3b

fi
